### PR TITLE
feat: use https://github.com/srghma/my-purescript-package-sets

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by srghma** [comment]
didnt mean to merge https://github.com/purescript-graphql-client/purescript-graphql-client/pull/13

reverted

> as a dotfile in a different repo? 

yes, I have extracted it to https://github.com/srghma/my-purescript-package-sets

can add you to it as a developer

**Comment by srghma** [comment]
about `we should pin repos`

yes, It's painful when something breaks

but would prefer not to pin

the reason this that I want all my repos to be up-to date

and I want my repos to break, because I intend to keep them up-to date

@toastal

**Comment by toastal** [comment]
You can't have them be up-to-date though. Spago will cache them just like the issue I started my day with. Unless you're constantly wiping your caches, this will be an issue.

**Comment by toastal** [comment]
In fact, just now after pulling upstream, I wasn't able to build because one of the downstream dependencies was updated. I had to remove my `.spago` directory and repull all packages. This completely ruins reproducible builds.

**Comment by toastal** [comment]
Even with the sha256 on your personal Dhall files, I can expect that file to be reproducible, but not the contents pulled down. This is a janky workflow to have to clear caches, versus, slapping the commit hash on it and knowing consumers should get exactly what they expect.

**Comment by toastal** [comment]
Looks like I have a failing build due to a cache issue too https://travis-ci.org/github/purescript-graphql-client/purescript-graphql-client/builds/724855247

**Comment by toastal** [comment]
This seems to have a caching issue too https://travis-ci.org/github/purescript-graphql-client/purescript-graphql-client/builds/724847726

**Comment by srghma** [comment]
> Unless you're constantly wiping your caches 

I do indeed `rmf .spago output && spago build --watch` a lot

_____

will check failures

**Comment by srghma** [comment]
all this is about pinning vs non-pinning

I don't know about good solution to automatically pin repos (e.g. for nix I use https://github.com/srghma/dotfiles/blob/master/nixos/pkgs/arion/update.sh scripts OR nixpkgs have updaterScript https://github.com/NixOS/nixpkgs/blob/e71c525eb710989bb7362506730745764df4e1ad/pkgs/tools/security/tor/default.nix#L59 )

and I'm fine with failures for now

____

will use github actions https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/main/.github/workflows/stale.yml because I cannot find how to cache `.spago` based on dhall hash

**Comment by toastal** [comment]
Ah, I've only just started using Nix via `home-manager`

**Pull request merged**
